### ISSUE TITLE
App image is loading slowly on app page

### ISSUE THREAD

**Issue by agazso** [felfele/felfele.org#10]
Its size can be reduced to make it faster, because the image size is 1419x1719 but the website only displays it at 473x573.

**Comment by vujevits** [comment]
added smaller image for mobile, on desktop retina it looked ugly.

**Comment by agazso** [comment]
My issue was that it's slow to load the image on the page, because it has a big size and we don't even need the big size, because on the client we downsize it.

I suggest to use a 473x573 image on desktop.
