### ISSUE TITLE
App page in Firefox returns Corrupted Content Error

### ISSUE THREAD

**Issue by agazso** [felfele/felfele.org#11]
Somehow the request url becomes `https://felfele.com/offline-plugin-app-shell-fallback/index.html`, then nginx does a redirect from this to the .org page which returns this error.

Seems to be a problem with gatsby.

<img width="1425" alt="Screen Shot 2019-05-10 at 16 08 14" src="https://user-images.githubusercontent.com/230163/57533433-0cb70b80-733e-11e9-8f0b-fa01ecea419d.png">

**Comment by vujevits** [comment]
gatsby sites have offline support, this screen happens only if you use .com and you don't have internet connection.
