### ISSUE TITLE
Footer is not responsive on mobile

### ISSUE THREAD

**Issue by agazso** [felfele/felfele.org#5]
The links in the footer are hard to access from mobile. It would be better to show the items as a segmented list.

<img width="487" alt="Screen Shot 2019-05-06 at 10 42 47" src="https://user-images.githubusercontent.com/230163/57215002-ff231e00-6feb-11e9-9cbe-bdd37234fd5e.png">

**Comment by vujevits** [comment]
Yes this should be fixed. What do you mean by segmented list?

**Comment by agazso** [comment]
It should look like this:
- Develop
  - Github
  - Guidelines
- Contribute
  - Donate

etc.
